### PR TITLE
Remove missed callback_guard

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/glib/pull/250

Forgot some manual calls

@GuillaumeGomez

### CODE REVIEW

**Comment by EPashkin** [comment]
Hm, seems all rt.rs need removing

**Comment by EPashkin** [comment]
Or better leave  with `assert_initialized_main_thread` with `#[allow(unused_macros)]`?
Currently it sole macro in `rt.rs` and unused in generated code.

**Comment by GuillaumeGomez** [comment]
We should really move all the macros inside a common crate. It'd make such things simpler. Anyway, if they're not used, just remove them.

**Comment by EPashkin** [comment]
Updated.

Moving to common crates IMHO impossible as these macros has different meaning in all your crates.

**Comment by EPashkin** [comment]
Single travis failure again.
@GuillaumeGomez  Maybe some timeouts need increase?

**Comment by EPashkin** [comment]
But no printing for 10min still strange, maybe it some infrastructure problem.

**Comment by GuillaumeGomez** [comment]
I think so. Let's merge. Thanks!

**Pull request merged**
