### PR TITLE
remove versions from git dependencies

### PR DESCRIPTION
**Pull request by vhdirk**
Same as https://github.com/gtk-rs/pangocairo/pull/20

### CODE REVIEW

**Comment by vhdirk** [comment]
Build seems to have failed for a single rust version due to network errors. All other build just fine.

**Comment by GuillaumeGomez** [comment]
You still have a conflict though. ;)

**Comment by vhdirk** [comment]
Yeah saw that just after my reply. Rebased it just now.

**Comment by GuillaumeGomez** [comment]
All good, thanks!

**Pull request merged**
