### PR TITLE
Add Pixbuf::new_from_xpm_data

### LINKED ISSUE #38: Missing Pixbuf::new_from_xpm_data
https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-xpm-data

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #38.

cc @EPashkin (Since you didn't seem to want to do it, I did :p)

### CODE REVIEW

**Comment by EPashkin** [comment]
Hm, I hoped that @hasufell test and add it, as I don't looked how this format need to be.
Its good, but IMHO better add it near other constructors.

**Comment by GuillaumeGomez** [comment]
Then let's put it up!

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by EPashkin** [comment]
Thanks, 👍

**Pull request merged**
