### PR TITLE
Fix Pixbuf::put_pixel when alpha channel disabled

### PR DESCRIPTION
**Pull request by cai-lw**
#59

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Good catch!

cc @EPashkin @sdroege

**Comment by sdroege** [comment]
Makes sense but will still explode on e.g. grayscale pictures, or not? Those should only have a single channel.

Also accessing the pixel data with that function is super inefficient :) Ideally there would be a way to get a `&[u8]` (and mut) for the pixel data, and the rowstride/etc. To directly work on the pixel data.

**Comment by GuillaumeGomez** [comment]
Good point, we should only write as many bytes as there are channels.

**Comment by cai-lw** [comment]
@sdroege The original documentation (https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-The-GdkPixbuf-Structure.html#GdkPixbuf--n-channels) says:
> Currently, only 3 or 4 samples per pixel are supported.

So there's no need to worry about grayscale pictures.

`Pixbuf::get_pixels` already exists, which returns the raw data as `&mut [u8]`. But I am now working on some computer graphics stuff that computes the image pixel by pixel, so I prefer to use `put_pixel` in this scenario.

**Comment by sdroege** [comment]
Maybe an assertion for the number of channels should be added then, to be sure this does not fall apart at a later time.

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Just waiting for CIs and then I merge. Thanks!

**Comment by sdroege** [comment]
CI is happy

**Pull request merged**
