### PR TITLE
Update versions.txt correctly to fix CI

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez Which other crates?

**Comment by GuillaumeGomez** [comment]
cairo and atk. More might be there.

**Comment by GuillaumeGomez** [comment]
gtk, pango and pangocairo as well. That should be the whole list.

**Comment by sdroege** [comment]
> gtk, pango

Will be fixed by my PRs to switch to once_cell

> pangocairo

Sending PR

**Comment by sdroege** [comment]
@GuillaumeGomez green

**Pull request merged**
